meta_product_name: "Notice"
meta_title: "Notice - Cours et fiches de Droit"
meta_description: "Notice accompagne les étudiants en Droit dans leurs révisions en fournissant cours actualisés et fiches de révision rédigés par des enseignants."
meta_image: "home_image2-min.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
