Rails.application.routes.draw do
  get 'favorites/index'
  get 'favorites/show'
  get 'favorites/new'
  get 'favorites/create'
  get 'favorites/delete'
  get 'reviews/index'
  get 'reviews/new'
  get 'reviews/create'
  get 'fiches/index'
  get 'fiches/show'
  get 'fiches/new'
  get 'fiches/create'
  get 'fiches/edit'
  get 'fiches/update'
  get 'chapters/index'
  get 'chapters/show'
  get 'chapters/new'
  get 'chapters/create'
  get 'chapters/edit'
  get 'chapters/update'
  get 'specialities/index'
  get 'specialities/show'
  get 'specialities/new'
  get 'specialities/create'
  devise_for :teachers, path: 'teachers'
  devise_for :students, path: 'students'
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
